# -*- coding: utf-8 -*-
"""get_household_meta_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UKefSH5fSHdKtfZtT3rbXcWXDkLZoZl6
"""

def get_household_meta_data(ID):
    """ returns meta information about household
    can be used to check the goodness of fit of results of rank_households()
    """
    household = Household(ID)
    print("Household", ID, ":", "\n")
    print("Number of occupants:", household.number_of_occupants)
    print("Number of drivers:",household.number_of_drivers)
    print("Number of cars:",household.number_of_cars)
    print("Net income:", household.income)
    print("Inhabitants in area:", household.population)
    print("Year of birth:", household.year_of_birth)
    print("Profession:", household.job)
    print("Driven distance in observation period:", household.driven_distance)