# -*- coding: utf-8 -*-
"""example_select_households.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UKefSH5fSHdKtfZtT3rbXcWXDkLZoZl6
"""

"""Example script on how to find a fitting household from dataset

Input data. Check readme for detailed information about the codes of the 
individual factors in the dataset.

1. Main factors (returned households will fulfill these factors):
  - number of occupants [int]
  - number of drivers [int]
  - number of cars [int]

2. Soft factors (The returned households are ranked based on how close they are 
to input. Factors are ranked based on chosen weight.):
  - income, w_income:           net income of household, weight
  - population, w_population:   # of inhabitants in area, weight
  - year_of_birth:              year of birth of first household member, weight
  - job:                        occupation of first household member, weight
  - distance:                   total driven distance by 1st hh member, weight
"""

input_number_of_occupants = 2
input_number_of_drivers = 2
input_number_of_cars = 1

input_income = 6
input_w_income = 0

input_population = 2
input_w_population = 0

input_year_of_birth = 1980
input_w_year_of_birth = 0

input_job = 1
input_w_job = 0

input_distance = 1000
input_w_distance = 1

###


households = rank_households(input_number_of_occupants,
                             input_number_of_drivers,
                             input_number_of_cars, 
                             input_income,
                             input_w_income,
                             input_population,
                             input_w_population,
                             input_year_of_birth,
                             input_w_year_of_birth,
                             input_job,
                             input_w_job,
                             input_distance,
                             input_w_distance)
print(households)