# -*- coding: utf-8 -*-
"""example_generate_profiles.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UKefSH5fSHdKtfZtT3rbXcWXDkLZoZl6
"""

""" Example script on how to create the following profiles of all cars from
selected hosuehold(s):

    - Consumption [kWh]
    - possbible charging power [kW]
    - state of charge [kWh]
    - charged power by car [kWh]
    - consumed power at charging station [kWh]

    Args:
    - *IDs:                 household ID or list of household IDs (if multiple)
    - start:                first timestep
    - end:                  last timestep
    - home_charging_power:  power of home charging station [kW]
    - work_charging_power:  power of work charging station [kW]
    - efficiency_home:      efficiency of home charging station, default: 0.95
    - efficiency_work:      efficiency of work charging station, default: 0.95
    - min_state_of_charge:  min possible state of charge in %, default = 10%
    - max_state_of_charge:  min possible state of charge in %, default = 90%
    - path:                 path to folder for csv.-file creation
    - bool_plot:            if true: plots are created, default: False
    - bool_create_csv:      if true: csv-files are created, default: False
"""

IDs = [4711031412, 4501024083, 4501022118, 4711030077, 4501023717]
start = 0
end = 1008
home_charging_power = 11
work_charging_power = 20
efficiency_home = 0.95
efficiency_work = 0.9
min_state_of_charge = 10  # [%]
max_state_of_charge = 100  # [%]
path = '/content/drive/MyDrive/Tobias_MA/Outputs/'
bool_plot = True
bool_create_csv = False

create_profiles(IDs = IDs,
                start = start,
                end = end,
                home_charging_power = home_charging_power,
                work_charging_power = work_charging_power,
                efficiency_home = efficiency_home,
                efficiency_work = efficiency_work,
                min_state_of_charge = min_state_of_charge,
                max_state_of_charge = max_state_of_charge,
                path = path,
                bool_plot = bool_plot,
                bool_create_csv = bool_create_csv