# -*- coding: utf-8 -*-
"""example_check_meta_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UKefSH5fSHdKtfZtT3rbXcWXDkLZoZl6
"""

""" Example script on how to check meta data for a household """

# Enter household ID
ID = 4711030214 

get_household_meta_data(ID)